name: bus-orel-front

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      BASE_URL: ${{secrets.BASE_URL}}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .env file
      run: |
          touch .env
          echo "BASE_URL=${{secrets.BASE_URL}}" >> .env
    - run: npm ci
    - run: npm run build --if-present

